export default [{
        id: 1,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/1.png?alt=media&token=b0d854c1-e52b-4a44-b816-628ec52ac584",
        title: "Web3Devs",
        category: "Development",
        description: "Web3Devs, a community for developers by a developer, its basic aim is to help developers get jobs, interships and freelancing opportunities. along with helping them with getting resources and learning materials. Web3Devs is a community for developers by a developer, its basic aim is to help developers get jobs, interships and freelancing opportunities. along with helping them with getting resources and learning materials.",
        discord: "https://discord.gg/sgYsfDKw",
        twitter: "https://twitter.com/Web3_Devs",
    },
    {
        id: 2,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/2.png?alt=media&token=89d4dd4f-2645-472e-8c09-b244c301735f",
        title: "Blockwee",
        category: "Design",
        description: "Blockwee offers next-gen professional services in field of Web 3.0. We provide our clients with specialised Web 3.0 marketing services targetted to scale and grow their products and services, training and consulting them.",
        discord: "https://discord.gg/AtMSfKCb",
        twitter: "https://twitter.com/blockwee",
        website: "https://blockwee.com/",
    },
    {
        id: 3,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/3.png?alt=media&token=c52a3c1b-8643-4daa-9eb6-5cfe8ececde2",
        title: "The Watermelon Gang",
        category: "Marketing",
        description: "Watermelon gang is a social media marketing gang that has been curating content for some of the biggest brands in the industry including Kotak Mahindra, CoinDCX exchange, dYdX exchange, Binance and a lot more!",
        website: "https://www.thewatermelongang.com/",
    },
    {
        id: 4,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/4.png?alt=media&token=c5ea75f0-f768-40f5-a70d-70d670e3adfa",
        title: "Bluelearn",
        category: "Education",
        description: "Bluelearn is India’s largest and smartest student community that enables students to learn new skills, grow their network, and get amazing opportunities in careers.",
        discord: "https://discord.gg/bluelearn",
        twitter: "https://twitter.com/bluelearn",
        website: "https://bluelearn.in/",
    },
    {
        id: 5,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/5.png?alt=media&token=90f45a47-a7d4-4b71-9d54-06db6e003569",
        title: "MarkitUp",
        category: "Content",
        description: "MarkitUp is a creative digital marketing agency that can help your brand unleash the power of content creation.",
        discord: "https://discord.gg/NG457cZP",
        twitter: "https://twitter.com/markitup_in",
        website: "https://markitup.in/",
    },
    {
        id: 6,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/6.png?alt=media&token=d6384d73-98bc-4315-be4c-e7da783fe27e",
        title: "Buidler's Tribe",
        category: "Education",
        description: "We are building an incubator DAO with a community governed fund and believe investment and support of Web3 companies need to be decentralised and global from Day 1.We are currently perfecting the deal flow, support and success models of this DAO by running a quasi traditional incubator.The operating team acts as a fulcrum that takes care of deal flow,curation and support.A tribe of institutions and individuals with knowledge and capital help the startups in a focused manner.        The success of Buidlerstribe is in the longevity of the networks that come through the DAO.",
        website: "https://buidlerstribe.com/",
        twitter: "https://twitter.com/buidlerstribe",
        discord: "https://discord.com/invite/buidlerstribe",
    },
    {
        id: 7,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/7.png?alt=media&token=ed05f5e4-cb9b-4c1c-bf28-6ae836a98899",
        title: "Moralis",
        category: "Software",
        description: "Moralis provides a single workflow for building high-performance apps. Fully compatible with your favourite web3 tools and services. Made by developers for developers. Join 150,000+ blockchain developers who build on  Moralis and utilized software and APIs to build & scale their apps without cost & complexity.",
        website: "https://moralis.io/",
        twitter: "https://twitter.com/MoralisWeb3",
        discord: "https://moralis.io/joindiscord/",
    },
    {
        id: 8,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/8.png?alt=media&token=d8c86ebb-cdd3-4076-a6c0-3b6d56255b01",
        title: "Web3 Events",
        category: "Events",
        description: "It is a platform, to bring the core of India's web3 community together. Wherein there is a pure value exchange-driven eco-system built to encourage, help, and make people more aware of web3 space.",
        twitter: "https://twitter.com/web3_events",
    },
    {
        id: 9,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/9.png?alt=media&token=ecf057d1-ac5b-4267-8028-088790d9efc4",
        title: "Dev.to",
        category: "Development",
        description: "DEV Community ‍ ‍ is a community of 980,224 amazing developers. We're a place where coders share, stay up-to-date and grow their careers.",
        website: "https://dev.to/",
    },
    {
        id: 10,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/10.png?alt=media&token=e7ef6878-6baf-49b7-964f-b91396593b06",
        title: "Surf Guild",
        category: "Gaming",
        description: "Surf Guild is a play-to-earn guild based on a global community. Helping 1 million people make a smooth transition from web2 to web3 by providing free web3 education and crypto games.",
        website: "https://surfguild.io/#/",
        twitter: "https://twitter.com/SurfGuild",
        discord: "https://discord.gg/surf-guild-986810133235519508",
    },
    {
        id: 11,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/11.png?alt=media&token=52fb9c40-90a7-4e57-b2e0-516002e40162",
        title: "Web3 Bharat",
        category: "Community",
        description: "Web3 Bharat (W3B) is a community that is bringing together curious minds pan India to spread awareness around Web3. Objective is to setup a Web3 ecosystem in tier-2/3/4 cities of India so as to drive adoption by creating a network of Web3 creators and consumers.",
        website: "https://web3bharat.xyz/",
        twitter: "https://twitter.com/web3bharat",
        discord: "https://discord.gg/8ebkETbF",
    },
    {
        id: 12,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/12.png?alt=media&token=a915d028-aa0d-48d1-a38e-5d58c41528b9",
        title: "Social 3",
        category: "Jobs",
        description: "Social3 is the first-ever Web3 based social hiring platform that incorporates a refer-&-earn model but for talent. Social3 also maintains your social Proof-of-work by verifying NFTs achieved through different Web3 EdTech startups.",
        website: "https://app.social3.club/",
        twitter: "https://twitter.com/Social3Club",
        discord: "https://discord.gg/Ypturn4F5A",
    },
    {
        id: 13,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/13.png?alt=media&token=aefa1705-d34d-4f69-bb7b-fbf37384663f",
        title: "Codedamn",
        category: "Education",
        description: "Learn industry level skillsets interactively in your browser. Codedamn enables anyone to learn and practice real-world programming skills and become industry relevant through our learning paths.",
        website: "https://codedamn.com/",
        twitter: "https://twitter.com/codedamncom",
        discord: "https://cdm.sh/discord",
    },
    {
        id: 14,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/14.png?alt=media&token=96825cec-44a2-4150-92fb-79126d6d1bc0",
        title: "Shardeum",
        category: "Crypto",
        description: "Shardeum is the world's first EVM-based L1 which uses dynamic state sharding to increase TPS with the addition of every new node.",
        website: "https://shardeum.org/",
        twitter: "https://twitter.com/shardeum",
        discord: "https://discord.gg/shardeum",
    },
    {
        id: 15,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/15.png?alt=media&token=33f6e622-5128-48a1-b5ec-14c02065697f",
        title: "Coders' Evoke",
        category: "Community",
        description: "Coders Evoke is a Platform that is established for Coding Enthusiasts and Freshers (Undergrads) to help them ace their Interviews and get Deep-Level Knowledge about the New Technologies in the Emerging Markets.",
        website: "http://codersevoke.us/?i=1",
        twitter: "https://twitter.com/coders_evoke",
        discord: "https://discord.gg/XMuEPgCj6y",
    },
    {
        id: 16,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/16.png?alt=media&token=fc9815a6-c34c-4b30-9e10-43845f48a2c4",
        title: "Clamp",
        category: "Crypto",
        description: "Clamp makes it extremely easy for anyone with zero or low crypto knowledge to start their crypto and DeFi journey with passive investment strategies.",
        twitter: "https://twitter.com/JoinClamp",
        website: "https://joinclamp.com/",
    },
    {
        id: 17,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/17.png?alt=media&token=5ddb5ec8-09ae-427d-860c-267d6893d850",
        title: "Plussha",
        category: "Gaming",
        description: "Upcoming web3 gaming ecosystem that will revolutionize gaming industry.Enjoy playing p2e games while earning",
        website: "https://plussha.com/",
        twitter: "https://twitter.com/PlusshaVerse",
    },
    {
        id: 18,
        image: "https://firebasestorage.googleapis.com/v0/b/commbuidl-3ccf5.appspot.com/o/18.png?alt=media&token=2f1f3b1f-3f2f-4b1f-9b1f-1f1f1f1f1f1f",
        title: "HyFi Blockchain",
        category: "Tech",
        description: "HyFi Blockchain is a network of blockchains for hybrid finance (HyFi). Hybrid finance combines the best of centralized & decentralized finance. ",
        website: "https://www.hyfiblockchain.com",
        twitter: "https://twitter.com/hyfi_blockchain",
        telegram: "https://t.me/hyfi_blockchain",
    },
    {
        id: 19,
        image: "",
        title: "Blockchain Magazine",
        category: "Tech",
        description: "Founded in 2016, Blockchain Magazine is the leading digital media platform covering diverse categories of news on blockchain technology, crypto assets, and emerging fin-tech trends. Each day, our team delivers the most accurate and up-to-date news from both the decentralized and centralized worlds.",
        website: "http://www.blockchainmagazine.net",
        twitter: "https://www.twitter.com/blockchainews/",
    },
    {
        id: 20,
        image: "",
        title: "Foundership - Web3 Startup Launcher 🚀 ",
        category: "Business",
        description: "CryptoSlate is a popular destination for crypto investors and blockchain enthusiasts. We provide breaking news, guides, price analysis, and educational content about Bitcoin, Ethereum, and other major cryptocurrencies.",
        website: "https://cryptoslate.com",
        twitter: "https://twitter.com/cryptoslate",
    }
];